### PR TITLE
Add functionality & improve docs

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
Hi! Thanks for your cool plugin :)

While working with it, I noticed that `change_keyword` for some reason needs both `url` and `oldshorturl` which seemed quite counter intuitive to me. Also the `title` parameter didn't exactly do what I wanted it to and `geturl` only returned one short url.

Hence, I went ahead and added some functionality. The changes are backwards compatible and I documented in the README, how exactly the functions work now.

TBH I'm not familiar with the internals of yourls and also I'm new to PHP, so I hope that my code is any good :D I tested everything on my local install, though and it works out fine.

I hope that the introduced functionality is to your liking :) Looking forward to a reply/review!

### CODE REVIEW

**Comment by timcrockford** [comment]
Hi @Bibo-Joshi! Just letting you know I've seen your pull request, but not going to have a proper chance to review it just yet (I will get to it though!). From memory the historical reason why both were required was because you can use the function to change the URL or the short URL, so I coded it to require both (I think, I wrote this plugin years ago now!)

Thank you for your pull request, and I promise I'll get to it soon!

**Comment by Bibo-Joshi** [comment]
Hi, thanks for the reply! No worries, I'm in no hurry :D
Regarding `change_keyword`: Passing both `oldshorturl` and `url` still works and will update both keyword and URL (though imho you might as well create a new shortlink, then …). To change only the URL, from my understanding `update` should be used instead, though. Also this is in fact not supported by `change_keyword` by neither the current version nor my PR.

**Comment by Bibo-Joshi** [comment]
Leaving a kind ping :)

**Review by Shyzer — APPROVED** [review]
This updated readme helped me get the parameters of the plugin working. Thank you both to Tim and Bibo!

**Comment by timcrockford** [comment]
Sorry it's taken to long to get this merged Bibo!

**Comment by Bibo-Joshi** [comment]
No worries :D Nice 👍

**Pull request merged**
